baseURL: "https://www.vincengocnguyen.com/"
languageCode: en-us
title: vinceNgocNguyen's meditations
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFeature: false
buildExpired: false

params: 
  env: production
  title: vinceNgocNguyen's meditations
  author: vinceNgocNguyen
  DateFormat: "January 2, 2006"
  defaultTheme: author
  disableThemeToggle: false

  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true
  disableScrollToTop: false
  comments: true

  profileMode:
    enabled: true
    imageUrl: /quyen_host-216x216.png
    imageTitle: Vince's avatar
    buttons:
      - name: About
        url: about   

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
